// import { createAsyncThunk } from '@reduxjs/toolkit';
// import { callApi } from 'wcf-component-lib/src/utils/apiServerSide';
// import { omitBy, isNil } from 'lodash';
// import { sliceName } from './types';

// //รายการสั่งจ่าย
// export const getRefundtoEmployerService = createAsyncThunk(
//   `${sliceName}/getRefundtoEmployer`, // เปลี่ยนชื่อ action type
//   (paymentType: string): RefundtoEmployerDataType[] => {
//     const data: RefundtoEmployerDataType[] = [
//       {
//         key: '1',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000001',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_office',
//         manage: '',
//       },
//       {
//         key: '2',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000002',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000001',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_banks',
//         manage: '',
//       },
//       {
//         key: '3',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000003',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000001',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_check',
//         manage: '',
//       },
//       {
//         key: '4',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000004',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000001',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_money',
//         manage: '',
//       },
//       {
//         key: '5',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000005',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_office',
//         manage: '',
//       },
//       {
//         key: '6',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000006',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000006',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_check',
//         manage: '',
//       },
//       {
//         key: '7',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000007',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000007',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_banks',
//         manage: '',
//       },
//     ];

//     //manipulate data by paymentType
//     const resultRefundtoEmployer = data.filter((item) => item.paymentType === paymentType);

//     return resultRefundtoEmployer;
//   },
// );
// //รายการสั่งจ่าย
// export const getPaymentDetailService = createAsyncThunk(
//   `${sliceName}/getPaymentDetail`, // เปลี่ยนชื่อ action type
//   (paymentNo: string): RefundtoEmployerDataType[] => {
//     const data: RefundtoEmployerDataType[] = [
//       {
//         key: '1',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000001',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_office',
//         manage: '',
//       },
//       {
//         key: '2',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000002',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000002',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_banks',
//         manage: '',
//       },
//       {
//         key: '3',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000003',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000003',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_check',
//         manage: '',
//       },
//       {
//         key: '4',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000004',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000004',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_money',
//         manage: '',
//       },
//       {
//         key: '5',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000005',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_office',
//         manage: '',
//       },
//       {
//         key: '6',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000006',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000006',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_check',
//         manage: '',
//       },
//       {
//         key: '7',
//         checkbox: false,
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000007',
//         bankAccountName: 'กาญจนา พิเศษ',
//         SSO_BRANCH_CODE: '1050',
//         paymentNo: '000000007',
//         offerer: '000 : อรุณเซอร์วิส แอนด์ ซัพพลาย',
//         amount: 1200000,
//         paymentType: 'p_banks',
//         manage: '',
//       },
//     ];

//     //manipulate data by paymentType
//     const resultPaymentDetail = data.filter((item) => item.paymentNo === paymentNo);

//     return resultPaymentDetail;
//   },
// );

// export const getChequeInfoListService = createAsyncThunk(
//   `${sliceName}/getChequeInfoList`, // เปลี่ยนชื่อ action type
//   (paymentNo: string): TableChequeType[] => {
//     const data: TableChequeType[] = [
//       {
//         id: '1',
//         paymentNo: '000000001',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '2',
//         paymentNo: '000000002',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '3',
//         paymentNo: '000000003',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '4',
//         paymentNo: '000000004',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '5',
//         paymentNo: '000000005',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '6',
//         paymentNo: '000000006',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '7',
//         paymentNo: '000000007',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//       {
//         id: '8',
//         paymentNo: '000000008',
//         chequeNo: '81020094',
//         bankCode: '006',
//         bankName: 'กรุงไทย จำกัด (มหาชน)',
//         bankAccountNo: '0000000001',
//         bankAccountName: 'นพดล สุขใจดี',
//         chequeStampDate: '2024-12-16',
//         amount: 1200000,
//         mode: 'view',
//       },
//     ];

//     //manipulate data by paymentType
//     const resultChequeInfoList = data.filter((item) => item.paymentNo === paymentNo);

//     return resultChequeInfoList;
//   },
// );
